NGAIF-Stories Chatbot.

Steps :

1. Created new directory 'Stories_Chatbot'.
2. Inside that directory/folder create new environment.
--> python -m venv chatbot
    Now, activate this 'chatbot' venv.
--> ./chatbot/Scripts/activate or .\chatbot\Scripts\activate (Any cmd will work)

3. In the process, 3 Problems/Errors came -
   Import "numpy" could not be resolved
   --> Command 'pip install numpy' solved this error.
   Import "nltk" could not be resolved
   Import "nltk.stem" could not be resolved
   --> Command 'pip install nltk' solved above both error.
   Import "tensorflow" could not be resolved
   --> Command 'pip install tensorflow' solved this error.
   Import "keras.models" could not be resolved
   --> Command 'from tensorflow.python.keras.models import load_model' solved this error.
       (Just replace original command "from keras.models import load_model" )
    
       Reference : https://stackoverflow.com/a/76540697/23533719

All Errors/Problems have solved by now.

5. Run the "main.py" file to train the Model.

Errors/Problems :
    In Line 12, SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
        Line 12 -> intents = json.loads(open('C:\Users\Raj\Desktop\ML_Internship\Stories_Chatbot\intents.json').read())
    --> Just remove the path. Keep 'intents.json' file in same folder.
        Solution : intents = json.loads(open("intents.json").read())

    In Line 22, LookupError:
                **********************************************************************
                Resource punkt_tab not found.
                Please use the NLTK Downloader to obtain the resource:
                >>> import nltk
                >>> nltk.download('punkt_tab')
                For more information see: https://www.nltk.org/data.html

                LookupError:
                **********************************************************************
                Resource wordnet not found.
                Please use the NLTK Downloader to obtain the resource:
                >>> import nltk
                >>> nltk.download('wordnet')
                For more information see: https://www.nltk.org/data.html
        
        Line 22 -> wordList = nltk.word_tokenize(pattern)
    --> Just Install 'wordnet' & 'punkt_tab' from nltk.download. It is a one time process.

        This following block of code solve the error.

        def nltkcheck():
            nltk.download('wordnet')
            nltk.download('punkt')

        nltkcheck()

after troubleshooting these 2 errors. 
Model was successfully trained and process completed.

6. Run the "chatbot.py" file to get the output.

Errors/Problems :

    In Line 18, ValueError: ('Unrecognized keyword arguments:', dict_keys(['batch_shape']))
        Line 18 -> model = load_model('chatbot_model.h5')
    --> Worked Solution :
        1. import tensorflow as tf
        2. Command "model = tf.keras.models.load_model('chatbot_model.h5')" solved this error.
           (Just replace original command "model = load_model('chatbot_model.h5')" )
           Reference : https://stackoverflow.com/a/70495946/23533719
    
        Earlier Soluton :
        Command 'from tensorflow.python.keras.models import load_model' solved this error.
        (Just replace original command "from keras.models import load_model" )
        Reference : https://stackoverflow.com/a/76540697/23533719

after rectifying all the errors we got the expected output. 

7. Creating a Flask Web applicattion.

Process : 1. Install the Python Flask Library.
          --> pip install Flask
          2. Run "app.py" file.

